language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ppuerto
  password:
    secure: vUEJDEaNWevSH1ST5hB70ON4IYtdTyVjznGdsfEoskau5FXb7W4jiK0T6Pe7Opz+g//fG4qUFS6OcWKtLStFAtoZM07jopMfbD+vfJKlfTuC+kgy+CZ3+j/iMeFpFnZ7bZp3EImXuyVupYXdFBT5fYyv7Jkedib1CylHZQJs9jznuheXiaJwIrvao7v3IqKjTTMfps6ACvcVFiuYfYJgWFbpTtaXPO/eTe8ywv6PFLj/KhtD9vfWybJkOfvKut1+bWD9Vt/Px3nZSc0vvVnrl0/nNq7Sip1GzfQ8TF9Raap8LCRNBAa5Ljefg3eI7VRFMMQ6f4FBzPc3i3EAPz1mfr8y2+3tF8pnd4V797J+eogfjIvkCwaROoouSvqGpdh+y+Mb/e+LfEqf5fWoRZRnLgO9cu7vlHMpWnkmpoU06S83YkGhztF2OUVF/ZjLKmwpdOGnxJocztc+xs2aAB+keTEIh+CSiy4ruJDtaGEkbxjiNGQOUJnQx2Acqr7SfUPwp8DQaMME6c58GUkwjO+qRMGoDrt4Uv2eXVMMjpyW9CrHkIGNARsldv9mfT1jRvS+RXJib5Y5prwSLMG2PZCyV6Y96pqQD/AaVrcfdnvhM/zHH7nQV950NOHKilgtgVkJJIe2amV5quun1dahjctuXTt6tUs/3K9xEeTj59k9bQw=
  on:
    tags: true
    repo: ppuertocrem/osef
    python: 3.6
